"""create review_events table

Revision ID: 71689db7a0a3
Revises: d8a36f1300a8
Create Date: 2026-07-23 17:12:54.986902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71689db7a0a3'
down_revision: Union[str, Sequence[str], None] = 'd8a36f1300a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.Integer(), nullable=False),
    sa.Column('before_step', sa.Integer(), nullable=True),
    sa.Column('before_stability', sa.Float(), nullable=True),
    sa.Column('before_difficulty', sa.Float(), nullable=True),
    sa.Column('before_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_state', sa.Integer(), nullable=False),
    sa.Column('after_step', sa.Integer(), nullable=True),
    sa.Column('after_stability', sa.Float(), nullable=True),
    sa.Column('after_difficulty', sa.Float(), nullable=True),
    sa.Column('after_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('after_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_card_id'), 'review_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_events_reviewed_at'), 'review_events', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_review_events_user_id'), 'review_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_events_user_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_reviewed_at'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_card_id'), table_name='review_events')
    op.drop_table('review_events')
    # ### end Alembic commands ###
