"""add fsrs scheduling fields to cards

Revision ID: d8a36f1300a8
Revises: 1446bb4c5ccb
Create Date: 2026-07-15 12:13:13.186399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a36f1300a8'
down_revision: Union[str, Sequence[str], None] = '1446bb4c5ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('fsrs_state', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('fsrs_step', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('stability', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('due', sa.DateTime(timezone=True), nullable=False))
    op.add_column('cards', sa.Column('last_review', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_cards_due'), 'cards', ['due'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_due'), table_name='cards')
    op.drop_column('cards', 'last_review')
    op.drop_column('cards', 'due')
    op.drop_column('cards', 'difficulty')
    op.drop_column('cards', 'stability')
    op.drop_column('cards', 'fsrs_step')
    op.drop_column('cards', 'fsrs_state')
    # ### end Alembic commands ###
